name: Deploy

on: [push]

jobs:
  pack-unitypackage:
    runs-on: ubuntu-20.04
    name: Pack Unity Package
    if: github.event_name == 'push'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: unity_develop
          fetch-depth: 0
      - name: Find all meta files
        run: |
          echo "Assets.meta" > metaList
          echo "Examples.meta" > metaList
          echo "Src.meta" > metaList
          find Assets/ -name \*.meta >> metaList
          find Examples/ -name \*.meta >> metaList
          find Src/ -name \*.meta >> metaList
      - name: Make directory for our unity package
        run: mkdir a
      - name: Create Unity Package
        uses: pCYSl5EDgo/create-unitypackage@v1.1.1
        with:
          package-path: 'a/io.liquiid.univeralauthenticatorlibrary.unitypackage'
          include-files: metaList
      - name: Upload package
        uses: actions/upload-artifact@v1
        with:
          name: a
          path: ./a
  
  split-full-upm:
    name: split upm_full branch
    runs-on: ubuntu-20.04
    needs: pack-unitypackage
    if: github.event_name == 'push'
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: unity_develop
        fetch-depth: 0
    - name: split upm_full branch
      run: |
        git branch -d upm_full &> /dev/null || echo upm branch not found # recreate the upm branch each time
        git config --global user.name 'github-bot'
        git config --global user.email 'github-bot@users.noreply.github.com'
        git checkout -b upm_full                                            # checkout the branch
        git rm -r .github
        git commit -am "removed workflow files"
        git push -u origin upm_full --force                              # commit the branch

  split-canvas-upm:
    name: split upm_canvas branch
    runs-on: ubuntu-20.04
    needs: split-full-upm
    if: github.event_name == 'push'
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: unity_develop
        fetch-depth: 0
    - name: split upm_canvas branch
      run: |
        git branch -d upm_canvas &> /dev/null || echo upm branch not found # recreate the upm branch each time
        git config --global user.name 'github-bot'
        git config --global user.email 'github-bot@users.noreply.github.com'
        git checkout -b upm_canvas                                            # checkout the branch
        git rm Examples/UiToolkit.meta
        git rm -r Examples/UiToolkit
        git rm -r .github
        git commit -am "removed workflow files"
        git push -u origin upm_canvas --force                              # commit the branch
  
  split-uitoolkit-upm:
    name: split upm_uitoolkit branch
    runs-on: ubuntu-20.04
    needs: split-canvas-upm
    if: github.event_name == 'push'
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: unity_develop
        fetch-depth: 0
    - name: split upm_uitoolkit branch
      run: |
        git branch -d upm_uitoolkit &> /dev/null || echo upm branch not found # recreate the upm branch each time
        git config --global user.name 'github-bot'
        git config --global user.email 'github-bot@users.noreply.github.com'
        git checkout -b upm_uitoolkit                                            # checkout the branch
        git rm -r Examples/Canvas
        git rm Examples/Canvas.meta
        git rm -r .github
        git commit -am "removed workflow files"
        git push -u origin upm_uitoolkit --force                              # commit the branch
  
  release:
    runs-on: ubuntu-20.04
    needs: split-uitoolkit-upm
    if: github.event_name == 'push'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Determine version
        run: echo "VERSION=$(git describe --tags --dirty)" >> $GITHUB_ENV
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1.12.0
        with:
          tag: 1.0.1
          name: Release 1.0.1
          body: ${{ env.VERSION }}
          makeLatest: true
      - name: Download unity package
        uses: actions/download-artifact@v1
        with:
          name: a
          path: ./a
      - name: Upload unity package to release
        uses: Fhwang0926/upload-release-asset@v1.1.17
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_name: a/io.liquiid.univeralauthenticatorlibrary.unitypackage # path + filename



